/**
 * Barre latérale du site de documentation.
 *
 * Choix : UNE SEULE barre latérale, entièrement AUTO-GÉNÉRÉE depuis l'arborescence de
 * `docs/`. Justification :
 *
 *  1. Une barre manuelle serait une seconde source de vérité à maintenir. Sa panne
 *     typique — créer une page puis oublier de la déclarer — produit une page en ligne
 *     mais INVISIBLE : exactement le genre d'échec silencieux que ce dépôt combat
 *     ailleurs (voir le job « gate » de la CI, qui existe pour la même raison).
 *  2. L'ordre et les libellés restent entièrement pilotables sans toucher à ce fichier :
 *     `sidebar_position` dans l'en-tête de chaque page, `_category_.json` par dossier.
 *  3. Les seules choses qu'apporte une barre manuelle — regrouper des pages de dossiers
 *     différents, insérer un lien externe au milieu de l'arborescence — ne servent pas ici.
 *
 * Échappatoire si le besoin apparaît un jour : remplacer l'entrée 'autogenerated' par la
 * liste explicite. Rien d'autre ne change dans le site.
 */
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  documentationSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
